### ISSUE TITLE
OnBehalfOf uses wrong variable

### ISSUE THREAD

**Issue by carvery** [jasoth/ADAL.PS#1]
The *OnBehalfOf section in the switch passes $Scopes as the first parameter, and $Scopes is not defined anywhere else in the script. Looking at the documentation for the call, I suggest that $Scopes should be changed to $Resource
https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_Microsoft_IdentityModel_Clients_ActiveDirectory_ClientCredential_Microsoft_IdentityModel_Clients_ActiveDirectory_UserAssertion_

**Comment by jazuntee** [comment]
I believe this is fixed now but I recommend switching to MSAL.PS now.
